EdenEast/nightfox.nvim

lua/nightfox/theme.lua
=> feat(theme): Add `LspCodeLens` hlgroup

extra/nightfox/nightfox_iterm.itermcolors, extra/nordfox/nightfox_iterm.itermcolors, extra/palefox/nightfox_iterm.itermcolors, lua/nightfox/extras/init.lua, lua/nightfox/extras/iterm.lua, lua/nightfox/util.lua
=> feat(extras): Generate Iterm2 colorscheme

extra/nightfox/nightfox_fish.fish, extra/nordfox/nightfox_fish.fish, extra/palefox/nightfox_fish.fish, lua/nightfox/extras/fish.lua
${purple} should be ${magenta}
=> Fixes #28: issue with ${purple} appearing in rendered fish extra

lua/nightfox/config.lua, lua/nightfox/theme.lua, readme.md
This change adds the option to enable inverse highlighting to nightfox's
configuration.
Fixes: #31
=> feat: Add inverse selection options to config

colors/nightfox.vim, colors/nordfox.vim, colors/palefox.vim
This allows `:colorscheme nordfox` and `:colorscheme palefox`.
=> ✨ Add nordfox and palefox as individual colorschemes

lua/nightfox/theme.lua, lua/nightfox/util.lua
=> fix: `colors_name` is reflected in variant used

readme.md
quick fix for example. just in case.
=> fix the example config

lua/nightfox/theme.lua, readme.md
Support for nvim-ts-rainbow. See https://github.com/p00f/nvim-ts-rainbow
=> Added support for nvim-ts-rainbow

lua/nightfox/pallet/nightfox.lua, lua/nightfox/precompiled/nightfox_compiled.lua, minimal_init.lua
Slightly brighten nightfox's conceal and border color `bg4` hsv `value`
by 3.
Related to #82
=> fix(pallet): Brighen bg4 `value` by 3

lua/nightfox/group/editor.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua
=> fix(group): Comment out `MsgArea`

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/neotree.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua, readme.md, usage.md
Adds support for https://github.com/nvim-neo-tree/neo-tree.nvim
=> add neo-tree support

lua/nightfox/main.lua
steps to see what's the problem
```ex
colorscheme nightfox
colorscheme duskfox
colorscheme nightfox
```
=> fix: reload precompiled modules

lua/nightfox/group/modules/gitsigns.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua
Noticed that changed lines were red and removed lines were yellow, and spotted that the two were inverted in the module.
Included the compiled version with this commit since it looked sane this time!
=> Fix swapped changed/removed for gitsigns

lua/nightfox/palette/duskfox.lua, lua/nightfox/palette/terafox.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/terafox_compiled.lua
This change increases the contrast of search results.
Related to: #74
=> fix(palette): Update `duskfox` and `terafox` `sel1`

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/notify.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua, lua/nightfox/precompiled/terafox_compiled.lua, readme.md, usage.md
=> feat(module): Add nvim-notify

extra/dawnfox/nightfox_kitty.conf, extra/dayfox/nightfox_kitty.conf, extra/duskfox/nightfox_kitty.conf, extra/nightfox/nightfox_kitty.conf, extra/nordfox/nightfox_kitty.conf, extra/terafox/nightfox_kitty.conf, lua/nightfox/extra/kitty.lua
=> chore(extra): Add comment for optional cursor none

lua/nightfox/lib/compile.lua
=> fix(compile): Guard missing opts

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/aerial.lua, lua/nightfox/precompiled/nvim/dawnfox_compiled.lua, lua/nightfox/precompiled/nvim/dayfox_compiled.lua, lua/nightfox/precompiled/nvim/duskfox_compiled.lua, lua/nightfox/precompiled/nvim/nightfox_compiled.lua, lua/nightfox/precompiled/nvim/nordfox_compiled.lua, lua/nightfox/precompiled/nvim/terafox_compiled.lua, lua/nightfox/precompiled/viml/dawnfox_compiled.lua, lua/nightfox/precompiled/viml/dayfox_compiled.lua, lua/nightfox/precompiled/viml/duskfox_compiled.lua, lua/nightfox/precompiled/viml/nightfox_compiled.lua, lua/nightfox/precompiled/viml/nordfox_compiled.lua, lua/nightfox/precompiled/viml/terafox_compiled.lua, readme.md, usage.md
This PR adds support for [Aerial.nvim](https://github.com/stevearc/aerial.nvim)
=> Add aerial support

extra/dawnfox/nightfox_windows_terminal.json, extra/dayfox/nightfox_windows_terminal.json, extra/duskfox/nightfox_windows_terminal.json, extra/nightfox/nightfox_windows_terminal.json, extra/nordfox/nightfox_windows_terminal.json, extra/terafox/nightfox_windows_terminal.json, lua/nightfox/extra/windows_terminal.lua
=> fix(extra): Add cursor and selection for windows term

lua/nightfox/util/template.lua
=> fix(template): Correctly call `to_css`

minimal_init.lua, misc/feline.lua, misc/tabby.lua, readme.md
People have asked about my statusline and tabline shown in the readme. Since these are my custom configurations I have linked to my dotfiles. My dotfiles are complex and have a lot to them. It is a great source of information for the mode seasoned user that maintains their own configuration, but for those that are just starting they are very confusing.
This change adds my feline and tabby configurations into their own single consumable file that can be added to another's configuration.
Relates: #172
=> Feline and Tabby example

readme.md
=> docs: Document multiple setup calls

readme.md
This change adds the icon from @keifererikson pr #181.
Resolves: #181
=> Add logo from @keifererikson

usage.md
Fix the type in the usage file as the docs are generated from this file.
=> fix typo in Palette Section

extra/dawnfox/nightfox_wezterm.toml, extra/dayfox/nightfox_wezterm.toml, extra/duskfox/nightfox_wezterm.toml, extra/nightfox/nightfox_wezterm.toml, extra/nordfox/nightfox_wezterm.toml, extra/terafox/nightfox_wezterm.toml, lua/nightfox/extra/wezterm.lua
=> feat(extra): Update wezterm with retro tab

extra/dawnfox/nightfox_wezterm.toml, extra/dayfox/nightfox_wezterm.toml, extra/duskfox/nightfox_wezterm.toml, extra/nightfox/nightfox_wezterm.toml, extra/nordfox/nightfox_wezterm.toml, extra/terafox/nightfox_wezterm.toml, lua/nightfox/extra/wezterm.lua
Compiled latest wezterm and ran from cmdline. Loaded resolved generated files and verified that it loads correctly.
Relates: #196
=> fix(extra): Use correct keys for bg and fg

lua/nightfox/util/lualine.lua
=> fix(lualine): Inactive `c` fg set to fg3

readme.md
I copy pasted this code into my editor and my LSP showed me that a comma was missing in this example
=> added missing comma in code example

lua/nightfox/util/lualine.lua
This change explicitly defines the table for each mode.
Resolves: #237 
Relates: #216
=> fix(lualine): Explicitly make table instead of generating

lua/nightfox/init.lua
=> fix(config): Config options now given correct table

extra/carbonfox/nightfox_warp.yaml, extra/dawnfox/nightfox_warp.yaml, extra/dayfox/nightfox_warp.yaml, extra/duskfox/nightfox_warp.yaml, extra/nightfox/nightfox_alacritty.yml, extra/nightfox/nightfox_iterm.itermcolors, extra/nightfox/nightfox_kitty.conf, extra/nightfox/nightfox_konsole.colorscheme, extra/nightfox/nightfox_warp.yaml, extra/nightfox/nightfox_wezterm.toml, extra/nightfox/nightfox_windows_terminal.json, extra/nightfox/nightfox_xresources.Xresources, extra/nordfox/nightfox_warp.yaml, extra/terafox/nightfox_warp.yaml, lua/nightfox/extra/warp.lua, misc/extra.lua
nightfox themes for [warp](https://www.warp.dev/)
=> feat: warp themes

extra/carbonfox/nightfox_tmux.tmux, extra/dawnfox/nightfox_tmux.tmux, extra/dayfox/nightfox_tmux.tmux, extra/duskfox/nightfox_tmux.tmux, extra/nightfox/nightfox_tmux.tmux, extra/nordfox/nightfox_tmux.tmux, extra/terafox/nightfox_tmux.tmux, lua/nightfox/extra/tmux.lua
use {bg} color as text color instead of {blue}
#256
=> update tmux font color

lua/nightfox/lib/compiler.lua, lua/nightfox/lib/vim/compiler.lua, lua/nightfox/util/init.lua
Reference from [catppuccin@4c5a2ebb](https://github.com/catppuccin/nvim/commit/4c5a2ebb250c2e3f1a6a05f372fead0a0988981e).
Resolves: #261
=> feat(compiler): handle errors in compiled results

lua/nightfox/lib/native_bit.lua
=> fix(compile): Add missing required bit functions

lua/nightfox/config.lua, lua/nightfox/lib/hash.lua, lua/nightfox/override.lua
Relates: [catppuccin#362](https://github.com/catppuccin/nvim/pull/362)
=> fix(compile): bit error on aarch64 with hash func

lua/nightfox/group/modules/treesitter.lua
<div>
</div>
<div>
</div>
<br/>
Resolves: #272
=> feat(treesitter): add checked and unchecked highlight

lua/nightfox/group/modules/treesitter.lua
Use the correct table for yaml fields.
Resolves: #274
=> fix(treesitter): correct yaml field

readme.md
=> chore(docs): update interactive mode gif

lua/nightfox/lib/compiler.lua, lua/nightfox/lib/vim/compiler.lua
Also shrink compiled binary size with alias `vim.api.nvim_set_hl` to `h`.
=> perf(compiler): remove `require` to write compiled files

readme.md
The old feline repo has been archived, and there will be a new maintainer to keep developing it but in the new repo. 
see details https://www.reddit.com/r/neovim/comments/116av04/comment/j99m5hj/?context=3
=> doc: update feline.nvim url

lua/nightfox/config.lua, lua/nightfox/group/modules/lsp_semantic_tokens.lua
catppuccin/nvim#427
rose-pine/neovim#141
=> feat: add new lsp semantic token highlight groups

extra/carbonfox/nightfox_kitty.conf, extra/dawnfox/nightfox_kitty.conf, extra/dayfox/nightfox_kitty.conf, extra/duskfox/nightfox_kitty.conf, extra/nightfox/nightfox_kitty.conf, extra/nordfox/nightfox_kitty.conf, extra/terafox/nightfox_kitty.conf, extra/zellij/nightfox.kdl, lua/nightfox/config.lua, lua/nightfox/extra/kitty.lua
=> fix(kitty): add "cursor_text_color" parameter

.github/workflows/release.yml
This PR fixes failing "release" workflow on PRs [(example)](https://github.com/mrtnvgr/nightfox.nvim/actions/runs/4618531956).
=> fix(release): rename "branch" -> "branches"

.github/workflows/extra.yml
=> feat(ci): add github action to autogenerate extra files

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/indent_blankline.lua, readme.md, usage.md
close #345 
Default:
Colored indent blankline:
=> feat(modules): add indent_blankline

lua/nightfox/group/modules/indent_blankline.lua
=> fix(indent_blankline): style wasn't set correctly

lua/nightfox/lib/compiler.lua
=> fix(compiler): add file permission error

lua/nightfox/lib/vim/compiler.lua
=> fix(vim): resolve deprecation of nested `[[`

flake.lock, flake.nix, lua/nightfox/lib/vim/compiler.lua
=> fix(vim): loadstring (5.1) vs load (5.2>=)

extra/carbonfox/carbonfox.ghostty, extra/dawnfox/dawnfox.ghostty, extra/dayfox/dayfox.ghostty, extra/duskfox/duskfox.ghostty, extra/nightfox/nightfox.ghostty, extra/nordfox/nordfox.ghostty, extra/terafox/terafox.ghostty, lua/nightfox/extra/ghostty.lua, misc/extra.lua
I refactored the extra generation. While I was doing this I tried to modify the pr #395 but had some issues pushing the rebase. Creating this quick pr instead for simplicity. See #395 for more details.
Closes: #395 .
=> feat(extra): add ghostty support

extra/carbonfox/alacritty.toml, extra/dawnfox/alacritty.toml, extra/dayfox/alacritty.toml, extra/duskfox/alacritty.toml, extra/nightfox/alacritty.toml, extra/nordfox/alacritty.toml, extra/terafox/alacritty.toml, lua/nightfox/extra/alacritty.lua
was getting following errors:
```
Unused config key: dim_forground
Unused config key: bright_forground
```
=> fix(extra): fix typo from forground to foreground

lua/nightfox/group/modules/treesitter.lua
=> fix(treesitter): '@comment.note' correctly set

extra/carbonfox/carbonfox.tmTheme, extra/dawnfox/dawnfox.tmTheme, extra/dayfox/dayfox.tmTheme, extra/duskfox/duskfox.tmTheme, extra/nightfox/nightfox.tmTheme, extra/nordfox/nordfox.tmTheme, extra/terafox/terafox.tmTheme, lua/nightfox/extra/bat.lua, misc/extra.lua
Add themes for [bat](https://github.com/sharkdp/bat) in the extra folder.
=> feat(extra): add bat themes
