lua/nightfox/theme.lua
There is an issue in the theme file that was setting `TermCursor` and
`TermCursorNC` and there were no values. Removing these files resolves
the issue.
Fixes: #7
=> fix(terminal): Resolve issue with terminal cursor

lua/nightfox/colors/nightfox.lua, lua/nightfox/colors/nordfox.lua, lua/nightfox/colors/palefox.lua
There was an issue with diff text being set to blue, making the text
unreadable. This change solved the issue by darkening the diff.text
color to make it more readable.
Fixes: #9
Result of new change
=> fix: Darken DiffText to make readable

lua/nightfox/util.lua
This fixes an issue with lualine where the bar's colors would be cleared
after util.load was called. Making sure that `ColorScheme` autocmd is
executed solved that issue.
=> fix(autocmd): Do autocmd `ColorScheme` after load

colors/nightfox.vim, lua/lightline/colorscheme/nightfox.lua, lua/lualine/themes/nightfox.lua, lua/nightfox/colors/init.lua, lua/nightfox/colors/nightfox.lua, lua/nightfox/colors/nordfox.lua, lua/nightfox/colors/palefox.lua, lua/nightfox/config.lua, lua/nightfox/extras/init.lua, lua/nightfox/init.lua, lua/nightfox/theme.lua, lua/nightfox/util.lua, readme.md
⚠️BREAKING CHANGE⚠️
This pr outlines changes made to move configuration from global variables to lua setup and load functions. This change deprecates the old global variables in favor of the lua `setup` function. Nightfox prints a warning to the user about the depreciation.
An issue will be pinned about the deprecation.
New configuration looks like this:
```lua
local nightfox = require('nightfox')
nightfox.setup({
fox = "nordfox"
})
nightfox.load()
```
Fixes #19
=> refactor: Configuration moved to lua

readme.md
=> docs: Document that `.load()` can take a fox's name

lua/nightfox/theme.lua
The names of the highlight groups changed in this PR: https://github.com/neovim/neovim/pull/15585
This updates the names, as well as assigns the values to the old group names to support earlier versions of Neovim
=> Fix diagnostic color support  for Neovim HEAD

lua/nightfox/colors/init.lua, lua/nightfox/config.lua, lua/nightfox/init.lua, lua/nightfox/util.lua, readme.md
Vim also have lua support. Since we doesn't depend on neovim features, it's easy to make it also compatible to vim.
=> Add vim support

lua/nightfox/theme.lua
This PR adds support for new highlight groups introduced in cmp: https://github.com/hrsh7th/nvim-cmp#highlights
Example:
=> cmp highlight support

autoload/lightline/colorscheme/nightfox.vim, lua/lightline/colorscheme/nightfox_vim.lua, lua/nightfox/util.lua
The original `nightfox` only supports `LightLine` on Neovim, because Vim doesn't has `v:lua.require()`. Therefore, I use `luaeval()` function to load the color table and support `Lightline` on Vim.
=> feat: support Lightline for Vim

readme.md
I couldn't apply this theme to my NeoVim in Terminal (default Mac terminal). By installing it on ITerm2.
voilà!!!
Life has come back to color.
=> sugestion for Mac Users

lua/nightfox/theme.lua
Currently, if the transparent option is set, Nvim Tree will still use
the solid background color configured in the colors table. As it stands
there is no way to make so that the side window matches the transparency
of the main window.
This change proposes a change targeted only to NvimTree. If accepted
this approach could be use more generally by replacing the c.bg_sidebar
with none and not having to check each time bg_sidebar is used.
=> [Nvim-Tree] Configure a transparent background if 'transparent' is set

lua/nightfox/lib/highlight.lua
=> fix(lib): `highlight` takes inverse for nvim api call

lua/lualine/themes/dawnfox.lua, lua/lualine/themes/dayfox.lua, lua/lualine/themes/duskfox.lua, lua/lualine/themes/nordfox.lua, readme.md
Lualine checks the value of `vim.g.colors_name` to load the appropriate
theme file. This change defines a lua theme foreach style.
Note: colorscheme should be set before calling lualine.setup()
so that `vim.g.colors_name` is set.
Resolve: #83
=> fix(lualine): Define theme for each style

lua/nightfox/lib/highlight.lua
vim.fn.has() returns 0 or 1 instead of true or false
Resolves: #85
=> fix(lib): Fix guard for nightly hl command

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/modes.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua, readme.md, usage.md
This Pr adds support for [modes.nvim](https://github.com/mvllow/modes.nvim)
I tried to add support using nightfox's colors with bg values but had issues with modes.nvim as it was very buggy at the moment of implementation. I am having a hard time getting the statusline to co-operate. I am using this `minimal_init.lua` for testing:
```lua
-- `minimal_init.lua` used for reproducing neovim issues
-- Open with `nvim --clean -u minimal_init.lua`
local root_tmp = vim.fn.has("win32") == 1 and os.getenv("TEMP") or "/tmp"
local install_path = root_tmp .. "/nvim/site/pack/packer/start/packer.nvim"
local compile_path = install_path .. "/plugin/packer_compiled.lua"
vim.opt.packpath = "/tmp/nvim/site"
local function load_plugins()
local packer = require("packer")
local use = packer.use
packer.reset() …
```
=> feat(modules): Add modes.nvim support

lua/nightfox/group/editor.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua
CursorLine and CursorColumn should be linked. CursorLine is the more
common setting of the two so should be the one that is defined.
Relates to: #90
=> fix(group): Swap link of `CursorLine` and `CursorColumn`

readme.md
This change explains that only non-default options are required to be
set by the user's configuration.
Relates: #73
=> docs(readme): Add options example

lua/nightfox/group/modules/tsrainbow.lua
Looks like there's a typo in the ts-rainbow highlight names; I was getting searing red brackets instead of nice nightfox red ones, and the colour order of nested ones didn't match.
I did run `make compile` but it seems to have introduced a bunch of additional changes beyond the `rainboe`/`rainbow` fixes, so I'm not sure if you want that or not, so I've not included it. Happy to do patch-add just the necessary lines if you want, but wanted some guidance since I've not worked on this project before.
```
nightfox.nvim % git st
M lua/nightfox/precompiled/dawnfox_compiled.lua
M lua/nightfox/precompiled/dayfox_compiled.lua
M lua/nightfox/precompiled/duskfox_compiled.lua
M lua/nightfox/precompiled/nightfox_compiled.lua
M lua/nightfox/precompiled/nordfox_compiled.lua
nightfox.nvim % git diff | …
```
=> Fix typo in ts-rainbow highlight names

doc/nightfox.txt, usage.md
I added {value} range for `Color:lighten()`, `Color: brighten()` and `Color: saturate()` that was not mentioned in `doc.txt` and `usage.md`. 
Thanks.
=> docs(help): Add the range for {value}

extra/duskfox/nightfox_konsole.colorscheme, extra/duskfox/nightfox_tmux.tmux, lua/nightfox/group/editor.lua, lua/nightfox/palette/duskfox.lua, lua/nightfox/precompiled/dawnfox_compiled.lua, lua/nightfox/precompiled/dayfox_compiled.lua, lua/nightfox/precompiled/duskfox_compiled.lua, lua/nightfox/precompiled/nightfox_compiled.lua, lua/nightfox/precompiled/nordfox_compiled.lua, lua/nightfox/precompiled/terafox_compiled.lua
This change increases the contrast between folds fg and bg by moving the bg from `bg3` to `bg2`. This is what folds were supposed to be.
Duskfox also has increased the brightness of fg3 (line numbers and and fold fg). As well it also added slightly more contrast between `fg1` (default) and `fg2` (alt).
Resolves: #120
=> fix(palette): Increase contrast for `duskfox` folds

readme.md
I realized there were some issues with the example. Namely "commnets" typo and a missing comma.
Tested with my config and it worked after changes.
=> docs(readme): Fix default option example

lua/nightfox/group/editor.lua
`nvim_set_hl` does not know what `inverse` is but `reverse` works for both.
Resolves: #133
=> Change inverse to reverse

lua/nightfox/palette.lua, lua/nightfox/spec.lua, lua/nightfox/util/template.lua, readme.md
This pr updates overrides for `palettes` and `specs` to take an `all` table. Values defined in this table will apply to **all** styles. This makes something like overriding a spec for example a lot easier.
From:
```lua
require("nightfox").setup({
specs = {
nightfox = { syntax = { operator = "orange", }, },
dayfox = { syntax = { operator = "orange", }, },
duskfox = { syntax = { operator = "orange", }, },
dawnfox = { syntax = { operator = "orange", }, },
nordfox = { syntax = { operator = "orange", }, },
terafox = { syntax = { operator = "orange", }, },
},
})
```
To
```lua
require("nightfox").setup({
specs = {
all = {
syntax = {
operator = "orange",
},
},
},
})
```
=> `all` override for `palette` and `spec`

lua/nightfox/lib/compile.lua, lua/nightfox/lib/highlight.lua, lua/nightfox/main.lua, lua/nightfox/precompiled/nvim/dawnfox_compiled.lua, lua/nightfox/precompiled/nvim/dayfox_compiled.lua, lua/nightfox/precompiled/nvim/duskfox_compiled.lua, lua/nightfox/precompiled/nvim/nightfox_compiled.lua, lua/nightfox/precompiled/nvim/nordfox_compiled.lua, lua/nightfox/precompiled/nvim/terafox_compiled.lua
There is an issue with setting `Normal` highlight using `nvim_set_hl`.
When getting the results with `nvim_get_hl_by_name("Normal", true)` this
returns:
```
{
[true] = 6
}
```
The workaround is to make `Normal` a special case at the end and set it
with `:highlight` until this bug is resolved.
Relates: #139
=> fix(lib): Hackly workaround for neovim core bug

doc/nightfox.txt, lua/nightfox/group.lua, lua/nightfox/lib/compile.lua, lua/nightfox/main.lua, lua/nightfox/util/deprication.lua, readme.md, usage.md
`palette` and `spec` can both be overridden per style but `group` was not. This change makes all override tables work the same.
```lua
require("nightfox").setup({
groups = {
CursorColumn = { bg = "sel0", link = "" },
IncSearch = { bg = "palette.cyan" },
},
})
```
```lua
require("nightfox").setup({
groups = {
all = {
CursorColumn = { bg = "sel0", link = "" },
IncSearch = { bg = "palette.cyan" },
},
},
})
```
=> `groups` option per style

doc/nightfox.txt, lua/nightfox/override.lua, readme.md, usage.md
Instead of having to know that the highlight group you are overriding is
is linked and setting `link` = '' this is done automatically for you.
=> fix(setup): `group` override defaults `link` to ''

extra/dawnfox/nightfox_wezterm.toml, extra/dayfox/nightfox_wezterm.toml, extra/duskfox/nightfox_wezterm.toml, extra/nightfox/nightfox_wezterm.toml, extra/nordfox/nightfox_wezterm.toml, extra/terafox/nightfox_wezterm.toml, lua/nightfox/extra/wezterm.lua, misc/extra.lua
This is for #183 #156 and for wezterm to properly parse the metadata content for nightfox  related toml tempmlates.
also update comment referring to cmd to run to generate the templates
=> add metadata toml fields for wezterm

lua/nightfox/util/lightline.lua
Lightline also changes the tabline. The tabline as a special value
called `tabsel` that sets the color for the selected tab.
This change updates the way that lightline colorschemes are generated to
account for this field.
=> fix(lightline): Define correct `tabline` fields

readme.md
This change shows a setup function with all primary keys. This shows
that `options`, `palettes`, `specs`, and `groups` are all in the same
level in the table.
Relates: #192
=> docs: Show full example of setup function

lua/nightfox/group/editor.lua, lua/nightfox/group/syntax.lua
The diff* highlight groups are highlight groups that apply to the `diff`
filetype. This was confusing between DiffChange and diffChanged. Moving
to the syntax group file and comments should clarify the highlight
groups.
Relates: #192
=> fix(syntax): Move diff* highlight groups under syntax

lua/nightfox/spec.lua
This change uses the correct name when loading all specs from palettes.
Resolves: #192
=> fix(spec): Use correct name to apply override

autoload/lightline/colorscheme/carbonfox.vim
carbonfox was missing the support for lightline. I have fixed.
```vim
let g:lightline.colorscheme = 'carbonfox'
```
=> fix: Rename invalid autoload variable

lua/nightfox/group/editor.lua, lua/nightfox/group/modules/treesitter.lua
This change cleans up treesitter and only supports the current valid format with `@` as a prefix. This helps with maintenance.
This change also cleans up highlight groups to make certain highlight groups stand out from eachother.
`@text` was expanded to help wit markdown.
BREAKING CHANGE: `TS*` highlight groups are removed.
=> refactor(treesitter): Support current format only

lua/nightfox/fingerprint.lua, lua/nightfox/init.lua, lua/nightfox/lib/vim/init.lua
Hashing the user's filename handles user configuration from the `/nix/store`.
Resolves: #253
=> fix(cache): user filename used in user cache check

usage.md
typo, the link on top wasn't working to the Modules section
=> typo Module instead of Modules

lua/nightfox/group/modules/navic.lua
Treesitter is not enabled by default when using `vim`. This checks to see if treesitter module is enabled before trying to link to treesitter highlight groups.
=> fix(module): use treesitter links only if module enabled

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/modules/tsrainbow2.lua, readme.md, usage.md
This adds support for the one of the new `ts-rainbow` maintained forks that is getting a rewrite and has different highlight groups: https://github.com/HiPhish/nvim-ts-rainbow2
=> feat: add support for ts-rainbow2

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/lib/colorblind.lua, lua/nightfox/palette.lua, readme.md, usage.md
This change adds support for a colorblind or color vision deficiency (cvd) mode. This mode implements a daltonization algorithm that shifts color to ranges that cvd people can see which helps create contrast with colors.
Resolves: #89
=> feat(cvd): support colorblind mode with daltonization

lua/nightfox/lib/hash.lua
~~This pr optimizes the hash function used to compute checksums for cached values. This is achieved by serializing a table into a minimum string representation and then performing the `dj2b` hashing algorithm on this string.~~
This pr optimizes the dj2b function by removing `{ string.byte }` because it is only faster when the string is very long, which isn't the case for configurations
Benchmarks were on both main and perf branch.
```lua
local t = require("nightfox.config").options
local hash = require("nightfox.lib.hash")
local function bench(msg, f, iter)
iter = iter or 1000
local sum = 0
for _ = 1, iter do
local start = vim.loop.hrtime()
f()
sum = sum + (vim.loop.hrtime() - start)
end
print(msg, sum / iter / 1000000)
end
bench("perf", function()
hash(t)
end, 10000)
```
| branch | time …
=> perf(hash): optimize hash function

lua/nightfox/init.lua
Having the `did_setup` value after the load function was causing cache misses as the flag was not set even when calling setup before load.
Resolves: #330
=> fix(cache): move setup guard before load call

extra/zellij/nightfox.kdl, lua/nightfox/extra/zellij.lua
Zellij's theme uses black for the background panels. This make it more in line with the rest of the themes
Here are some examples
=> fix(extra): zellij black and white set to bg3/fg3

lua/nightfox/group/modules/treesitter.lua
Within the Treesitter module, the group `@label.json` was previously using `fg = spec.func` to color JSON labels as functions.
However the spec `func` is nested in `spec.syntax.func` not in `spec.func`, which caused incorrect highlighting of JSON labels.
By using `syn.func`, which correctly points to `spec.syntax.func`, the issue is now resolved.
=> fix(syntax): Fix highlight for json labels

doc/nightfox.txt, lua/nightfox/group/modules/diagnostic.lua, lua/nightfox/palette/carbonfox.lua, lua/nightfox/palette/dawnfox.lua, lua/nightfox/palette/dayfox.lua, lua/nightfox/palette/duskfox.lua, lua/nightfox/palette/nightfox.lua, lua/nightfox/palette/nordfox.lua, lua/nightfox/palette/terafox.lua, lua/nightfox/spec.lua, misc/feline.lua, usage.md
Neovim 0.9 added a new `DiagnosticOk` highlight https://github.com/neovim/neovim/pull/21286
=> feat: add new DiagnosticOk highlight

doc/nightfox.txt, flake.lock, lua/nightfox/config.lua, lua/nightfox/group/modules/lazy.lua, readme.md, usage.md
Lazy.nvim used CursorLine and VisualSelect to differentiate between active and non-active buttons at the top of lazy's ui. These are the same styles in nightfox.
This was overridden to help make active button visually unique.
The Dimmed and Prop highlight groups were linked to `Conceal`. As this makes the text too concealed on the darker background this was changed to be slightly more contrasting while keeping then still dimmed.
=> fix(groups): differentiate between active button with lazy.nvim

lua/nightfox/group/editor.lua
Relates to default colorscheme change in neovim [#26334](https://github.com/neovim/neovim/pull/26334)
Resolves: #386
=> fix(group): WinSeperator defined along side VertSplit

lua/nightfox/group/modules/whichkey.lua
The WhichKey window should be treated as a floating window, which benefits users with transparent backgrounds without affecting the display of no-transparent ones.
What's more, the original ` spec.bg0 ` is not conducive to the user's simple customization of this highlight
thus，user can simplely use ` NormalFloat = { fg = "fg1", bg = "NONE", }, ` to set most of the float windows to transparent
=> Set the background highlight of WhichKey to "NormalFloat"

lua/nightfox/group/modules/treesitter.lua
with fallback highlight groups.
Related to https://github.com/nvim-treesitter/nvim-treesitter/issues/4799#issuecomment-1860154411.
=> feat(treesitter): follow upstream highlight groups

lua/nightfox/group/modules/treesitter.lua
The `Function` highlight group exists and is defined here
https://github.com/EdenEast/nightfox.nvim/blob/7e9487875dc5f69a2fd6f60d3a3ef4fb457b57c1/lua/nightfox/group/syntax.lua#L19
I assume this was just a typo in the recent Great Migration of Treesitter Highlights
=> fix: link to correct Function highlight group

doc/nightfox.txt, readme.md, usage.md
I noticed this while exploring the colorblind mode (thanks for that, by the way!).
=> documentation: Change spelling of "week" to "weak"

lua/nightfox/group/modules/notify.lua
Summary
----
This adds a missing highlight for notify-nvim, specifically `NotifyBackground` (linked to `NormalFloat`). Without this we receive a warning message from nvim-notify stating that `NotifyBackground` is unset for the colorscheme.
=> Add NotifyBackground missing highlight

doc/nightfox.txt, lua/nightfox/config.lua, lua/nightfox/group/syntax.lua, usage.md
The "PreProc" category has a group assigned to changing syntax colors, but not the style (bold, italic, etc). This is really useful for systems languages like C or Rust. For example, I cannot get `use` to show as bold when writing Rust.
Once it is fixed, I can make `use` bold, for example, like this.
Example with C using `#include`.
Fixes #429
=> Added custom styling for preprocessor macros

lua/nightfox/group/modules/neogit.lua, readme.md
The repo URL for neogit has changed from
https://github.com/TimUntersberger/neogit to
https://github.com/NeogitOrg/neogit. This PR updates the repo URL.
=> Update repo URL for neogit module

lua/nightfox/group/modules/mini.lua
Add explicit support for all new groups since #174 and for the (hopefully) upcoming 'mini.icons'.
=> feat(mini): add new highlight groups

extra/zellij/nightfox.kdl, lua/nightfox/extra/zellij.lua
- bg is used as text background color for selection in zellij instead of
background color of the zellij itself
- this causes no highlight on selection since both the terminal
background and highlight color is same
- updated bg color in zellij.lua to sel0
- refer: https://github.com/zellij-org/zellij/issues/2263
Signed-off-by: Avinal Kumar <avinal.xlvii@gmail.com>
=> fix(zellij): corrected text selection bg color

lua/nightfox/group/modules/treesitter.lua
Fix italics for markup files.
Tested with both markdown and latex, both of which were broken.
Before:
After:
=> Fix `@markup.italic`

lua/nightfox/group/syntax.lua
Resolves issue when using `dim_inactive` the brackets linked to Normal which defines a background color.
Resolves: #474
=> fix(syntax): link typescriptParens to brackets

lua/nightfox/config.lua, lua/nightfox/group/modules/blink.lua
Hello, 
Lately [blink.cmp](https://github.com/Saghen/blink.cmp) has been gaining popularity and has its own hlgroups for completion menus, similar to nvim-cmp.
While it currently has support for mapping to the nvim-cmp hlgroups with its setting `appearance.use_nvim_cmp_as_default`, eventually this may be removed once colorschemes support it more ubiquitously.
I adapted the colors and links directly from the existing cmp module, so please feel free to adjust anything to better suit the theme's visuals.
=> Add support for blink.cmp
